### ISSUE TITLE
New Songs

### ISSUE THREAD

**Issue by securing-ab** [jodacame/happi-dev-sdk#1]
Hi! I’m Ab and I use your API for my discord music bot (lyrics). There are a few songs the users of my bot would like to see in the lyrics system,one of them is **Good 4 U** by _Olivia Rodrigo_ an a lot of the new songs as well! 

Thanks!

(Posting here since I wasn’t able to email)

**Comment by jodacame** [comment]
We're added this track to queue. We have many of new albums in queue and this take a long time to process all, in a few weeks maybe you got this song in the api's response.
